[physique-mecanique.m1]
s1 = [
"UM4PY103",
"UM4PY1026",
"UM4PY122",
"UM4MESFI",
"UM4MET12",
"UM4MET13",
"UM4MEF10",
"UM4MEA10",
"UM4MES10",
]

s2 = [
"UM4LVAN2",
"UM4LVFR2",
"UM4MEP10",
"UM4MEF24",
"UM4MET20",
"UM4MESPY",
"UM4PY205",
"UM4PY226",
"UM4MEF22",
"UM4MEF23",
"UM4MEF28",
"UM4MEF29",
"UM4MES20",
"UM4MES21",
"UM4MES22",
"UM4MEA22",
"UM4MEA20",
]

[acoustique.m1]
s1 = [
"UM4MET10",
"UM4MET11",
"UM4MET12",
"UM4MET13",
"UM4MET14",
"UM4MEAIP",
"UM4MEA10",
"UM4MEA11",
]

s2 = [
"UM4LVAN2",
"UM4LVFR2",
"UM4MET20",
"UM4MEA20",
"UM4MEA21",
"UM4MEA22",
"UM4MEA23",
"UM4MEA24",
"UM4MEA25",
]

[fluides.m1]
s1 = [
"UM4MET10",
"UM4MET11",
"UM4MET12",
"UM4MET13",
"UM4MET14",
"UM4MESFI",
"UM4MEF10",
"UM4MEF11",
]

s2 = [
"UM4LVAN2",
"UM4LVFR2",
"UM4MET20",
"UM4MEF20",
"UM4MEF21",
"UM4MEF22",
"UM4MEF23",
"UM4MEF24",
"UM4MEF25",
"UM4MEF26",
"UM4MEF27",
"UM4MEF28",
"UM4MEF29",
]

[solides.m1]
s1 = [
"UM4MET10",
"UM4MET11",
"UM4MET12",
"UM4MET13",
"UM4MET14",
"UM4MESFI",
"UM4MES10",
"UM4MES11",
]

s2 = [
"UM4LVAN2",
"UM4LVFR2",
"UM4MET20",
"UM4MES20",
"UM4MES21",
"UM4MES22",
"UM4MES23",
"UM4MES24",
"UM4MES25",
"UM4MES26",
"UM4MES27",
"UM4MEF29",
]

[energetique.m1]
s1 = [
"UM4MET10",
"UM4MET11",
"UM4MET12",
"UM4MET13",
"UM4MET14",
"UM4MEEP1",
"UM4MEEIP",
"UM4MEE10",
"UM4MEE11",
]

s2 = [
"UM4LVAN2",
"UM4LVFR2",
"UM4MET20",
"UM4MEEP2",
"UM4MEE20",
"UM4MEE21",
"UM4MEE22",
"UM4MEE23",
]

[computational-mechanics.m1]
s1 = [
"UM4MET10",
"UM4MET11",
"UM4MET12",
"UM4MET13",
"UM4MET14",
"UM4MESFI",
"UM4MES10",
"UM4MEF10",
]

s2 = [
"UM4LVAN2",
"UM4LVFR2",
"UM4MET20",
"UM4MES20",
"UM4MES21",
"UM4MES22",
"UM4MES23",
"UM4MES24",
"UM4MES25",
"UM4MES26",
"UM4MES27",
"UM4MEF20",
"UM4MEF21",
"UM4MEF22",
"UM4MEF23",
"UM4MEF24",
"UM4MEF25",
"UM4MEF26",
"UM4MEF27",
"UM4MEF28",
"UM4MEF29",
]

[energetique.m2.aerien]
s3 = [
"UM5MEE00",
"UM5MEE01",
"UM5MEE02",
"UM5MEE03",
"UM5MEE04",
"UM5MEE05",
"UM5MEE12",
"UM5MET01",
"UM5MEE14",
"UM5MEE15",
"UM5MEE17",
"UM5MEE18",
"UM5MEE19",
"UM5MEE28",
"UM5MEE29",
"UM5MEE30",
"UM5MEES0",
]

s4 = [
"UM5MEES1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
"UM5MEE33",
"UM5MEE34",
"UM5MEE35",
"UM5MEE36",
]

[energetique.m2.cleaner]
s3 = [
"UM5MEE00",
"UM5MEE01",
"UM5MEE02",
"UM5MEE03",
"UM5MEE06",
"UM5MEE07",
"UM5MEE12",
"UM5MET01",
"UM5MEE14",
"UM5MEE15",
"UM5MEE17",
"UM5MEE18",
"UM5MEE20",
"UM5MEE28",
"UM5MEE29",
"UM5MEE30",
"UM5MEES0",
]

s4 = [
"UM5MEES1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
"UM5MEE33",
"UM5MEE34",
"UM5MEE35",
"UM5MEE36",
]

[energetique.m2.stb]
s3 = [
"UM5MEE00",
"UM5MEE01",
"UM5MEE02",
"UM5MEE03",
"UM5MEE08",
"UM5MEE09",
"UM5MEE12",
"UM5MET01",
"UM5MEE14",
"UM5MEE21",
"UM5MEE22",
"UM5MEE23",
"UM5MEE24",
"UM5MEE28",
"UM5MEE30",
"UM5MEE31",
"UM5MEES0",
]

s4 = [
"UM5MEES1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
"UM5MEE33",
"UM5MEE34",
"UM5MEE35",
"UM5MEE36",
]

[energetique.m2.imce]
s3 = [
"UM5MEE00",
"UM5MEE02",
"UM5MEE06",
"UM5MEE10",
"UM5MEE11",
"UM5MEE12",
"UM5MET01",
"UM5MEE14",
"UM5MEE16",
"UM5MEE25",
"UM5MEE26",
"UM5MEE27",
"UM5MEE24",
"UM5MEE28",
"UM5MEE30",
"UM5MEE32",
"UM5MEE38",
"UM5MEES0",
]

s4 = [
"UM5MEES1",
"UM5MEE37",
"UM5MEE34",
"UM5MEE35",
"UM5MEE36",
]


[energetique.m2.etn]
s3 = [
"UM5MEE00",
"UM5MEE01",
"UM5PYI09",
"UM5MEE10",
"UM5MEE11",
"UM5MEE16",
"UM5MEE21",
"UM5MEE22",
"UM5MEE24",
"UM5MEE23",
"UM5MEE32",
"UM5PYI04",
"UM5MEES0",
]

s4 = [
"UM5MEES1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
]

[acoustique.m2.ingenierie]
s3 = [
"UM5MEA01",
"UM5MEA02",
"UM5MET01",
"UM5MEA03",
"UM5MEA04",
"UM5MEA05",
"UM5MEA06",
"UM5MEA08",
"UM5MEA05",
"UM5MEA06",
"UM5MEA09",
"UM4MES11",
]

s4 = [
"UM5MEAS1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
]

[acoustique.m2.atiam]
s3 = [
"UM5IN457",
"UM5IN458",
"UM5MEAT1",
"UM5MEAT2",
"UM5MEAT3",
]

s4 = [
"UM5MEAS1",
"UM5MEOIP",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
]

[fluides.m2.aerodynamique]
s3 = [
"UM5MEF01",
"UM5MEF02",
"UM5MEF03",
"UM5MEF04",
"UM5MEF05",
"UM5MET01",
"UM5MEF06",
"UM5MEF07",
"UM5MEF08",
"UM5MEF09",
"UM5MEF10",
"UM5MEF11",
]

s4 = [
"UM5MEFS1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
]

[fluides.m2.fluid-mechanics]
s3 = [
"UM5MEF21",
"UM5MEF22",
"UM5MEF23",
"UM5MEF24",
"UM5MEF25",
"UM5MEF26",
"UM5MEF27",
"UM5MEF28",
"UM5MEF29",
"UM5MEF30",
"UM5MEF31",
"UM5MEF32",
"UM5MEF06",
"UM5MEF33",
"UM5MEF34",
"UM5MEFS0",
]

s4 = [
"UM5MEFS2",
]

[fluides.m2.msh]
s3 = [
"UM5MEF42",
"UM5MEF41",
"UM5MEF43",
"UM5MEF01",
"UM5MET01",
"UM5MEF02",
"UM5MEF44",
"UM5MEF45",
"UM5MEF06",
"UM5MEF09",
"UM5MEF11",
]

s4 = [
"UM5MEFS1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
]

[solides.m2.ms]
s3 = [
"UM5MES01",
"UM5MES02",
"UM5MES03",
"UM5MES04",
"UM5MES05",
"UM5MES06",
"UM5MES07",
"UM5MES08",
"UM5MES09",
"UM5MES10",
"UM5MES11",
"UM5MES12",
"UM5MES13",
"UM5MES14",
"UM5MES15",
"UM5MES16",
"UM5MES17",
"UM5MES18",
"UM5MES19",
"UM5MES20",
"UM5MES24",
"UM5MES25",
]

s4 = [
"UM5MESS1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
]

[solides.m2.amms]
s3 = [
"UM5MES01",
"UM5MES02",
"UM5MES03",
"UM5MES04",
"UM5MES05",
"UM5MES15",
"UM5MES16",
"UM5MES17",
"UM5MES08",
"UM5MES09",
"UM5MES10",
"UM5MES11",
"UM5MES12",
"UM5MES13",
"UM5MES14",
"UM5MES18",
"UM5MES19",
"UM5MES20",
"UM5MES21",
"UM5MES22",
"UM5MES23",
"UM5MES24",
"UM5MES06",
"UM5MES07",
"UM5MES25",
]

s4 = [
"UM5MESS1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
]

[solides.m2.dms]
s3 = [
"UM5MES01",
"UM5MES02",
"UM5MES20",
"UM5MES21",
"UM5MES22",
"UM5MES23",
"UM5MES24",
"UM5MES04",
"UM5MES05",
"UM5MES06",
"UM5MES07",
"UM5MES08",
"UM5MES09",
"UM5MES10",
"UM5MES11",
"UM5MES12",
"UM5MES13",
"UM5MES14",
"UM5MES15",
"UM5MES16",
"UM5MES17",
"UM5MES18",
"UM5MES19",
"UM5MES03",
"UM5MES25",
]

s4 = [
"UM5MESS1",
"UM5LVAN3",
"UM5LVAN5",
"UM4LVFR2",
]

[computational-mechanics.m2]
s3 = [
"UM5MES02",
"UM5MES04",
"UM5MEF21",
"UM5MEF03",
"UM5MES01",
"UM5MES03",
"UM5MES05",
"UM5MES06",
"UM5MES07",
"UM5MES08",
"UM5MES09",
"UM5MES10",
"UM5MES11",
"UM5MES12",
"UM5MES13",
"UM5MES14",
"UM5MES15",
"UM5MES16",
"UM5MES17",
"UM5MES18",
"UM5MES19",
"UM5MES20",
"UM5MES21",
"UM5MES22",
"UM5MES23",
"UM5MES24",
"UM5MES25",
"UM5MEF01",
"UM5MEF02",
"UM5MEF03",
"UM5MEF04",
"UM5MEF05",
"UM5MET01",
"UM5MEF06",
"UM5MEF07",
"UM5MEF08",
"UM5MEF09",
"UM5MEF10",
"UM5MEF11",
"UM5MEF21",
"UM5MEF22",
"UM5MEF23",
"UM5MEF24",
"UM5MEF25",
"UM5MEF26",
"UM5MEF27",
"UM5MEF28",
"UM5MEF29",
"UM5MEF30",
"UM5MEF31",
"UM5MEF32",
"UM5MEF33",
"UM5MEF34",
]

s4 = [
"UM5MECS1",
"UM5LVAN3",
"UM5LVAN5",
]
